server:
  port: 8080
cloud:
  aws:
    credentials:
      accessKey: AKIA2LW236WZKYH6BKGN
      #      accessKey: ${AWS_SECRET_KEY}
      secretKey: 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
    #      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: filotshopping
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  redis:
    host: redis://default:QfHSRSmjdXqMD0IoCYNG56bOADQsJ5Ed@redis-12214.c277.us-east-1-3.ec2.cloud.redislabs.com:12214

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FILOT_SHOP
    username: root
    password: dnjswhdtj1!
  #    username: ${DATABASE_USERNAME}
  #    password: ${DATABASE_PASSWORD}
  #    url: ${CLEARDB_DATABASE_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: visionwill3322@gmail.com
    password: pozohiqjzzcoaqjg
    #    username: ${MAIL_USERNAME}
    #    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database: mysql


logging:
  level:
    org.hibernate.SQL: debug



