server:
  port: 8080
cloud:
  aws:
    credentials:
      accessKey: AKIA2LW236WZK26AYGXW
      secretKey: 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
    s3:
      bucket: filotshopping
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FILOT_SHOP
    username: root
    password: dnjswhdtj1!



  mail:
    host: smtp.gmail.com
    port: 587
    username: visionwill3322@gmail.com
    password: pozohiqjzzcoaqjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database: mysql
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

logging:
  level:
    org.hibernate.SQL: debug







