server:
  port: 8080

spring:
  redis:
    host: redis://default:QfHSRSmjdXqMD0IoCYNG56bOADQsJ5Ed@redis-12214.c277.us-east-1-3.ec2.cloud.redislabs.com:12214

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FILOT_SHOP
    username: root
    password: dnjswhdtj1!
  #    username: ${DATABASE_USERNAME}
  #    password: ${DATABASE_PASSWORD}
  #    url: ${CLEARDB_DATABASE_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: visionwill3322@gmail.com
    password: pozohiqjzzcoaqjg
    #    username: ${MAIL_USERNAME}
    #    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database: mysql


logging:
  level:
    org.hibernate.SQL: debug



